import { extname } from 'path';
import type { AIContext, PRProposal, ProviderName } from '../types/index.js';
import { BaseProvider } from './base.provider.js';

const DIR_TYPE_MAP: Record<string, string> = {
  test: 'test', tests: 'test', __tests__: 'test', spec: 'test',
  docs: 'docs', doc: 'docs',
  '.github': 'ci', '.husky': 'chore', ci: 'ci',
  scripts: 'chore', migrations: 'chore',
  config: 'chore', configs: 'chore',
  types: 'refactor', interfaces: 'refactor',
  styles: 'style', css: 'style', scss: 'style',
};

const EXT_TYPE_MAP: Record<string, string> = {
  md: 'docs', mdx: 'docs',
  yml: 'ci', yaml: 'ci',
  sh: 'chore', ps1: 'chore',
  sql: 'chore',
  css: 'style', scss: 'style', less: 'style',
  test: 'test', spec: 'test',
};

export class HeuristicProvider extends BaseProvider {
  name: ProviderName = 'heuristic';

  async isAvailable(): Promise<boolean> {
    return true;
  }

  async generateCommitMessage(context: AIContext): Promise<string> {
    const { changedFiles, detectedCommitConvention: conv, ticket } = context;

    if (changedFiles.length === 0) {
      return `chore: update files`;
    }

    const type = inferType(changedFiles.map((f) => f.path));
    const scope = inferScope(changedFiles.map((f) => f.path), conv.allowedScopes);
    const subject = inferSubject(changedFiles.map((f) => f.path));
    const ticketSuffix = ticket ? ` (${ticket})` : '';

    const scopePart = scope ? `(${scope})` : '';
    const message = `${type}${scopePart}: ${subject}${ticketSuffix}`;

    return message.length <= conv.maxHeaderLength
      ? message
      : message.substring(0, conv.maxHeaderLength - 3) + '...';
  }

  async generatePRDescription(context: AIContext): Promise<PRProposal> {
    const { changedFiles, branch, ticket } = context;
    const files = changedFiles.map((f) => `- \`${f.path}\` (${f.status})`).join('\n');
    const ticketLine = ticket ? `\n\nRelated to: ${ticket}` : '';

    const title = buildPRTitle(branch, changedFiles.map((f) => f.path));

    const body = [
      `## Context`,
      `Changes from branch \`${branch}\`.${ticketLine}`,
      ``,
      `## Changes`,
      files,
      ``,
      `## Testing`,
      `- [ ] Manual testing performed`,
      `- [ ] Automated tests pass`,
      ``,
      `## Risks / Impact`,
      `_No known risks identified._`,
      ``,
      `## Additional Notes`,
      `_Generated by git-smart-flow heuristic provider._`,
    ].join('\n');

    return { title, body };
  }
}

function inferType(paths: string[]): string {
  const votes: Record<string, number> = {};

  for (const p of paths) {
    const parts = p.split('/');
    for (const part of parts) {
      const mapped = DIR_TYPE_MAP[part.toLowerCase()];
      if (mapped) votes[mapped] = (votes[mapped] ?? 0) + 1;
    }
    const ext = extname(p).slice(1).toLowerCase();
    const extMapped = EXT_TYPE_MAP[ext];
    if (extMapped) votes[extMapped] = (votes[extMapped] ?? 0) + 0.5;
  }

  if (Object.keys(votes).length === 0) return 'feat';

  return Object.entries(votes).sort(([, a], [, b]) => b - a)[0][0];
}

function inferScope(paths: string[], allowedScopes?: string[]): string | undefined {
  if (paths.length === 0) return undefined;

  const firstParts = paths.map((p) => p.split('/')[0]).filter((p) => !p.startsWith('.'));
  const common = mostCommon(firstParts);
  if (!common || common === 'src') {
    const secondParts = paths
      .filter((p) => p.includes('/'))
      .map((p) => p.split('/')[1])
      .filter(Boolean);
    const commonSecond = mostCommon(secondParts);
    if (commonSecond && (!allowedScopes || allowedScopes.includes(commonSecond))) {
      return commonSecond;
    }
    return undefined;
  }

  if (!allowedScopes || allowedScopes.includes(common)) return common;
  return undefined;
}

function inferSubject(paths: string[]): string {
  if (paths.length === 1) {
    const parts = paths[0].split('/');
    const filename = parts[parts.length - 1].replace(/\.[^.]+$/, '');
    return `update ${toKebab(filename)}`;
  }
  if (paths.length <= 3) {
    const parts = paths.map((p) => {
      const segs = p.split('/');
      return segs[segs.length - 1].replace(/\.[^.]+$/, '');
    });
    return `update ${parts.join(', ')}`;
  }
  const dirs = [...new Set(paths.map((p) => p.split('/')[0]))];
  return `update ${dirs.slice(0, 2).join(', ')} files`;
}

function buildPRTitle(branch: string, _paths: string[]): string {
  const cleaned = branch
    .replace(/^(feat|fix|feature|hotfix|chore|release)\//, '')
    .replace(/^[A-Z][A-Z0-9]+-\d+-/, '')
    .replace(/[-_]/g, ' ')
    .trim();
  return cleaned.charAt(0).toUpperCase() + cleaned.slice(1);
}

function mostCommon(arr: string[]): string | undefined {
  if (arr.length === 0) return undefined;
  const counts: Record<string, number> = {};
  for (const item of arr) counts[item] = (counts[item] ?? 0) + 1;
  const sorted = Object.entries(counts).sort(([, a], [, b]) => b - a);
  return sorted[0][0];
}

function toKebab(str: string): string {
  return str
    .replace(/([a-z])([A-Z])/g, '$1-$2')
    .replace(/[_\s]+/g, '-')
    .toLowerCase();
}
